# -*- coding: utf-8 -*-
"""SSNExtractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWIhXXIzJRMQzHDlkuDLfaviyTMNzL6G
"""


import re
import cv2
import regex
import easyocr
import platform
import multiprocessing

image=cv2.imread("/Users/adith/OneDrive/Desktop/resized.jpg")
reader = easyocr.Reader(['en'], model_storage_directory=r'C:\Users\adith\.EasyOCR',verbose=False)
results=reader.readtext(image)
regex=""

def findSSN(text):
    text = text.replace(' ', '').replace('*', '-').replace('–', '-').replace('_', '-')
    text = re.sub(r'[-]+', '-', text)
    digits = re.sub(r'\D', '', text)
    if len(digits) == 9:
            return f"{digits[:3]}-{digits[3:5]}-{digits[5:]}"
    return None

for _,text,confidence in results:
    if findSSN(text):
        print(text)